def getPrograms():
    return [
        "Accounting",
        "Animation",
        "Applied Management",
        "Applied Museum Studies",
        "Architectural Technician",
        "Architectural Technology",
        "Autism Studies",
        "Auto Body Repairer",
        "Automotive Service Technician",
        "Bachelor of Building Science",
        "Bachelor of Commerce",
        "Bachelor of Interior Design",
        "Bachelor of Public Safety",
        "Bachelor of Technology",
        "Baking and Pastry Arts",
        "Bartending",
        "Biotechnology",
        "Bookkeeping",
        "Brand Management",
        "Broadcasting Radio",
        "Business Accounting",
        "Business Agriculture",
        "Business Marketing",
        "Business Marketing",
        "Business Trades",
        "Business Administration",
        "Business Fundamentals",
        "Child and Youth Care",
        "Child and Youth Care",
        "Civil Engineering Technology",
        "Client Relations",
        "Commercial Estimating",
        "Computer Programming",
        "Computer Systems Technician",
        "Conflict Management",
        "Cook",
        "Creative Arts",
        "Creative Writing",
        "Culinary Management",
        "Culinary Skills",
        "Cyber Security Analysis",
        "Dental Assisting",
        "Dental Hygiene",
        "Digital Analytics",
        "Digital Health"
    ]